Repository ntacamp/404.notrollsallowed.com, pull requests merged in 2020-06, with the labels that each got.

#7 Smart Home: Sėkmės ir nesėkėmės, kuriant išmanius namus
  404.txt
Labels: Pending

#13 Laptop Casting: reusing all the laptop parts
  404.txt
Labels: Presentation

#15 Safe and practical intro to Rope Bondage
  404.txt
Labels: Activity, Presentation
