Repository ntacamp/404.notrollsallowed.com, pull requests merged in 2020-07, with the labels that each got.

#22 Homemade first person view for a RC plane. Progress report
  404.txt
Labels: Presentation

#17 Experience with payment systems (SEPA, UK, Asia, SWIFT)
  404.txt
Labels: Presentation

#25 Uniform UX across Linux and MacOS environments
  404.txt
Labels: Presentation

#24 Using math to make something pleasant to look at
  404.txt
Labels: Presentation

#26 Smart Hom^WFarm
  404.txt
Labels: Presentation

#27 "Mėsonomika": mėsos ir pieno istorija, politika ir ekonomika
  404.txt
Labels: Presentation

#16 The right environment for fast and simple development
  404.txt
  index.html
Labels: Pending

#12 Wakeboarding 101
  404.txt
Labels: Presentation

#29 Dangaus šviesulių stebėjimas teleskopu
  404.txt
Labels: Activity

#36 NTA t-shirt DIY
  404.txt
Labels: Activity

#37 Synths, Midi and FX. My path to wiring everything together
  404.txt
Labels: Presentation

#39 PR38 bLED - Blaze Light Emitting Display
  404.txt
Labels: Activity, Presentation

#41 (Ne)alaus mini degustacija
  404.txt
Labels: Activity

#42 Making your first D&D 5e player character
  404.txt
Labels: Activity

#43 What I learned from reverse-engineering document scanners
  404.txt
Labels: Presentation

#45 Gamtos fotografija - kas slepiasi už gero kadro
  404.txt
Labels: Presentation

#44 Stage lighting with MIDI: Arduino DMX controller
  404.txt
Labels: Presentation

#49 Cosmology 101 - Kodel visatai būtent 14 milijardų metų ir kitkas
  404.txt
Labels: Presentation

#48 Saulė (11m) praves workšopą ir kiekvienas galės pasidaryti sau apyrankę iš lazeriu pripautų karoliukų (iš akrilo likučiu - GREEN!!)
  404.txt
Labels: Activity

#47 Astronomical Sun observation
  404.txt
Labels: Activity

#46 Mano mamos Nokia ir kaip radau pažeidžiamimą Ežio appse
  404.txt
Labels: Presentation

#50 Add presentation "How to write a CPU emulator"
  404.txt
Labels: Presentation
