Repository ntacamp/404.notrollsallowed.com, pull requests merged in 2021-06, with the labels that each got.

#53 Added topic: Building mechanical keyboards
  404.txt
Labels: Presentation

#54 ID kortelės el. parašo aplikacija (-os): veikimas ir klaidos
  404.txt
Labels: Presentation

#55 CNC1419 (~350 €) vertės mini frezavimo/"drožimo" staklytės
  404.txt
Labels: Activity, Presentation

#56 Keyboard hacking. (custom layout, remaps, automation.)
  404.txt
Labels: Presentation

#57 Pabuskit! - kodo kokybė niekam neįdomi
  404.txt
Labels: Presentation

#58 How to be a great GM, the art of cooperative storytelling
  404.txt
Labels: Presentation

#60 Workshop for kids - laser cut toys, bracelets
  404.txt
Labels: Activity

#61 Kaip aš atradau, jog esu idiotas ir rekomenduočiau tai visiems
  404.txt
Labels: Presentation
