Repository ntacamp/404.notrollsallowed.com, pull requests merged in 2021-07, with the labels that each got.

#63 Italo (LADA automobilio) nuotykiai SSRS
  404.txt
Labels: Presentation

#64 Making maps using a consumer drone
  404.txt
Labels: Presentation

#62 Update 404.txt
  404.txt
Labels: Activity

#68 Kaip nustoti žudyti savo fikusą
  404.txt
Labels: Presentation

#69 PR69 Išmaniai išmanūs namai nerašant kodo
  404.txt
Labels: Presentation

#70 Lessons learned during NATO cybersecurity exercise
  404.txt
Labels: Presentation

#71 ARG - Alternatyvios realybės žaidimas
  404.txt
Labels: Presentation

#72 Tensegrity Structures Workshop
  404.txt
Labels: Activity

#73 Programming for goverment health care - the lessons learned
  404.txt
Labels: Presentation

#74 Potato baking in campfire workshop
  404.txt
Labels: Activity

#77 Linux konteineriai
  404.txt
Labels: Presentation

#78 Jumping into the weird end of the pool: juostinė fotografija
  404.txt
Labels: Presentation

#79 Kaleidoscope workshop
  404.txt
Labels: Activity

#80 Hidroponinis pomidorų auginimas ant palangės
  404.txt
Labels: Presentation

#81 Workaround censorship for your services
  404.txt
Labels: Presentation

#75 Monster Fog Machine
  404.txt
Labels: Activity

#82 Alaus protmūšis
  404.txt
Labels: Activity

#83 Mysterious Life Under Microscope
  404.txt
Labels: Activity

#84 Sonic Pi, arba kaip programuotojai gali groti su kompu
  404.txt
Labels: Presentation

#86 Papasakosiu apie tai kaip pasidaryti ir naudoti 34 klavišų klaviatūrą.
  404.txt
Labels: Pending, Presentation

#88 The unheard world of power line inspections
  404.txt
Labels: Presentation

#85 Kūdikių edukacija flash metodu
  404.txt
Labels: Presentation

#87 Kitesurfing. Bandysiu atkalbėt ir papasakosiu kaip pradėti
  404.txt
Labels: Pending, Presentation

#89 Neuroplastiškumas - kaip hakinti smegenis sau naudinga linkme
  404.txt
Labels: Presentation

#91 Improving your bike performance
  404.txt
Labels: Presentation

#93 Open-source Brain to Computer interface
  404.txt
Labels: Presentation

#94 Beer blind test
  404.txt
Labels: Activity

#95 Maistas visiems!
  404.txt
Labels: Activity

#96 Kaip iš internete rastų webcam'ų gaminau timelapse video
  404.txt
Labels: Presentation

#97 DIY 404-camp t-shirt workshop
  404.txt
Labels: Activity

#99 Update sound section
  404.txt
  index.html
Labels: Activity

#100 Art'o kūrimas žaidimams
  404.txt
Labels: Presentation

#102 QWERTY's flaws and the alternatives
  404.txt
Labels: Presentation

#103 Electric Smart, or fixing Mercedes's mistakes
  404.txt
Labels: Presentation

#101 Sąmoningumo meditacijos (angl. mindfulness meditation) užsiėmimas
  404.txt
Labels: Presentation
