Repository ntacamp/404.notrollsallowed.com, pull requests merged in 2023-07, with the labels that each got.

#183 Design Your Own ISA and Build a (Virtual) CPU
  404.txt
Labels: Presentation, 2023

#180 Hiking and camping with kids: survival guide for adults
  404.txt
Labels: Presentation, 2023

#185 Electric skateboarding workshop
  404.txt
Labels: Activity, 2023

#190 The Art of Mini Sumo: Strategy and Skill
  404.txt
Labels: Presentation, 2023

#186 How to music 101
  404.txt
Labels: Presentation, 2023

#187 Ghostbusters R.T.V - cosplay inžineriškai
  404.txt
Labels: 2023

#188 Antweight combat robot workshop
  404.txt
Labels: Activity, 2023

#189 Antweight presentation: Small Bots, Big Battles
  404.txt
Labels: Presentation, 2023

#191 Home-made second generation ROV
  404.txt
Labels: Presentation, 2023

#192 Automating financial decisions with AI
  404.txt
Labels: Presentation, 2023

#193 Update 404.txt
  404.txt
Labels: Activity, 2023

#194 Besikapstant po skaitmenines nuotekas
  404.txt
Labels: Presentation, 2023

#195 Šakočių kepimas
  404.txt
Labels: Activity, 2023

#196 Atsinešiu kelias sadhu lentutes kad galėtumės ant jų pastovėti
  404.txt
Labels: Activity, 2023

#197 Origami dirbtuvės
  404.txt
Labels: Presentation, 2023

#198 Oro filtravimas asmeninei ir kolektyvinei darbų saugai
  404.txt
Labels: Presentation, 2023

#199 Įspūdžiai, sprendimai bandant sumažinti elektros sąskaitą
  404.txt
Labels: Presentation, 2023

#200 Activity: LARP "What Actually Happened?"
  404.txt
Labels: Activity, 2023

#202 Severely overengineering differential steering gearbox
  404.txt
Labels: Presentation, 2023

#203 Paslaptingas bičių pasaulis: šeima, darbai, įdomybės
  404.txt
Labels: Presentation, 2023

#204 Small epoxy jewelry project including restoring pressure pot
  404.txt
Labels: Presentation, 2023

#205 Kodėl man trukčioja akis perkant el. knygas amazonėje?
  404.txt
Labels: Presentation, 2023

#201 Asmeniniai atradimai apie atmintį ir mokymąsį, klaidos & pamokos
  404.txt
Labels: Presentation, 2023

#207 An amateurs guide on how to make your own programming language
  404.txt
Labels: Presentation, 2023

#209 Apnea diving 101
  404.txt
Labels: Presentation, 2023

#211 Workshop: The Quiet Year - map-buildin/rpg/storry-telling
  404.txt
Labels: Activity, 2023

#212 [2023] Show and tell: oscilloscope music
  404.txt
Labels: Presentation, 2023

#206 Sea Shanties: Istorija & Trivia
  404.txt
Labels: Presentation, 2023

#218 Personal Story of Partly Succesfull Open-Source Side Project
  404.txt
Labels: Presentation, 2023

#219 300 km dviračiu vienu užsėdimu
  404.txt
Labels: Presentation, 2023

#222 Compiler from scratch
  404.txt
Labels: Presentation, 2023

#225 Workshop: AI in a box
  404.txt
Labels: Presentation, 2023

#226 Nintendo Wii gidas. Konsolės taikymas mokant vaikus skaityti
  404.txt
Labels: Presentation, 2023

#223 Daltonizmo emuliatorius
  404.txt
  index.html
Labels: Presentation, 2023

#228 Retro Bluetooth kolonėlė
  404.txt
Labels: Presentation, 2023

#229 The cosmic workshop for kids
  404.txt
Labels: Activity, 2023

#230 Vizualūs Efektai Pradedantiesiems
  404.txt
Labels: Presentation, 2023

#231 Topic: Technologijų karas
  404.txt
Labels: Presentation, 2023
