Repository ntacamp/404.notrollsallowed.com, pull requests merged in 2024-07, with the labels that each got.

#254 Attraction: Bookshelf of old IT-related books
  404.txt
Labels: Activity, 2024

#255 Using autonomous 2cm precision GPS lawnmower for a year
  404.txt
Labels: Presentation, 2024

#256 Waxing bike chains for fun and profit
  404.txt
Labels: Presentation, 2024

#257 Android Auto headunit from scratch
  404.txt
Labels: Presentation, 2024

#258 Lock picking workshop
  404.txt
Labels: Activity, 2024

#259 Bring your own T-Shirt and design. I will bring cutting plotter and t…
  404.txt
Labels: Activity, 2024

#262 Crokinole: learn to play workshop
  404.txt
Labels: Activity, 2024

#264 ARDF – elektroninių lapių medžioklė
  404.txt
  index.html
Labels: Activity, 2024

#265 Esu Mechanikas pas Ryanair'a, Avia mech darbo specifika +QA
  404.txt
Labels: Presentation, 2024

#267 Raktų pakabukų pynimo dirbtuvės
  404.txt
Labels: Activity, 2024

#268 Programų atestacijos Apple įrenginiuose problemos
  404.txt
Labels: Presentation, 2024

#269 Kas yra mėgėjiškas radijas?
  404.txt
  index.html
Labels: Presentation, 2024

#266 Badmintono pasižaidimai
  404.txt
Labels: Presentation, 2024

#270 Workshop: Blizgučių stotelė
  404.txt
Labels: Activity, 2024

#272 Burlentės - puikus sportas programuotojams
  404.txt
Labels: Presentation, 2024

#271 Vyrai ir pedikiūras: kodėl verta rūpintis savo pėdomis
  404.txt
Labels: Presentation, Pending, 2024

#273 DIY PAPR oro filtravimo sistema
  404.txt
Labels: Presentation, 2024

#274 PR274 Edukacija apie bites
  404.txt
Labels: Activity, 2024

#275 Rytinė mankšta su Lotynų Amerikos ritmai
  404.txt
Labels: Activity, 2024

#276 Kaip atspausdinti inkstą?
  404.txt
Labels: Presentation, 2024

#277 Suprasti paauglę: septynios pakopos į suaugusiųjų gyvenimą
  404.txt
Labels: Presentation, 2024

#278 PR278 Be emocijų nėra intelekto
  404.txt
Labels: Presentation, 2024

#281 Kaip išsirinkti dviratį
  404.txt
Labels: Presentation, 2024

#282 Blynų robotas
  404.txt
Labels: Presentation, Activity, 2024

#285 Moto trials - smagiau, saugiau, pigiau, daugiau progreso
  404.txt
Labels: Presentation, 2024

#287 RC plane upgrade with an autopilot and video streaming
  404.txt
Labels: Presentation, 2024

#288 Tingios pupelės: kaip informatikas pupeles auginti bando
  404.txt
Labels: Presentation, 2024

#289 Spagečių tilto iššūkis
  404.txt
Labels: Activity, 2024

#290 Let's create LLM party to replace Lithuanian government
  404.txt
Labels: Presentation, 2024

#291 SpikeBall aka Smūginis
  404.txt
Labels: Activity, 2024

#292 Automating 3D printing on repeat
  404.txt
Labels: Presentation, 2024

#294 Genų inžinerijos pagrindai - kaip gaminamas insulinas
  404.txt
Labels: Presentation, 2024

#296 Savanorystė. Kam man to reikia?
  404.txt
Labels: Presentation, 2024

#295 Kosminės meno dirbtuvės
  404.txt
Labels: Activity, 2024

#297 Update 404.txt with Osint presentation
  404.txt
Labels: Presentation, 2024
