Repository ntacamp/404.notrollsallowed.com, pull requests merged in 2025-05, with the labels that each got.

#305 Istorinis fechtavimas ilguoju kalaviju
  404.txt
Labels: Presentation, Activity, 2025

#306 Jausminis programavimas
  404.txt
Labels: Presentation, 2025

#307 Trainable Logic Gate Networks
  404.txt
Labels: Presentation, 2025

#309 Ką reiškia "būti šauliu"? Apie šaulystę atvirai
  404.txt
Labels: Presentation, 2025

#311 LogSeq: just another Notepad?
  404.txt
Labels: Presentation, 2025

#313 Soldering workshop 2025
  404.txt
Labels: Activity, 2025
